Remove custom scroll behavior, allow scroll physics customization, fix double scroll effects and double scroll bars
woltapp/wolt_modal_sheet pull request #103
Opened 2023-11-24 09:49 UTC by ulusoyca

## Description
Initially, we had a bad practice of hardcoding scroll behaviors and scroll physics in the package. This information has been an internal detail in the main content implementation, and causing confusion to the users.

This PR addresses the following:
* Removes custom `DragScrollBehavior` from all examples and the main content component in the scroll list.
* Demonstrates how to add a custom scroll behavior to `MaterialApp` in all of the examples.
* Adds a `scrollPhysics` field to the `ThemeData` to enable customizing of the physics in the main content custom scroll view. Adds an example to the ReadMe file for this field.
* Adds DeviceInfo package to the playground example to be able to test different overscroll effects on Android.

## Related Issues

* https://github.com/woltapp/wolt_modal_sheet/issues/102

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [-] My PR includes tests for *all* changed/updated/fixed behaviors.
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] The package compiles with the minimum Flutter version stated in the [pubspec.yaml](https://github.com/woltapp/wolt_modal_sheet/blob/main/pubspec.yaml#L8)

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[Contributor Guide]: https://github.com/woltapp/wolt_modal_sheet/blob/main/CONTRIBUTING.md

2023-11-28 23:04 UTC, TahaTesser requested changes
Overall looks good.  There are a bunch of changes in just one PR, preferably a cleaner and focused PR would be easier to test and review.

2023-11-29 15:25 UTC, ulusoyca commented on playground/lib/main.dart
> +      deviceInfo is AndroidDeviceInfo ? deviceInfo.version.sdkInt : 0;
But this is not part of the package. It is part of the example app. If I use io, I cant try this on Web.

2023-11-29 15:33 UTC, TahaTesser commented on playground/lib/main.dart
> +      deviceInfo is AndroidDeviceInfo ? deviceInfo.version.sdkInt : 0;
That's fair.

2023-12-12 12:59 UTC, yunusemrebakir approved these changes

2023-12-12 13:01 UTC, merged