Refactor deprecated location code
woltapp/wolt_modal_sheet pull request #146
Opened 2024-02-11 12:49 UTC by AcarFurkan

## Description

Since the location parameter was deprecated, I passed it to the uri parameter.

## Related Issues

#145 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes tests for *all* changed/updated/fixed behaviors.
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] The package compiles with the minimum Flutter version stated in the [pubspec.yaml](https://github.com/woltapp/wolt_modal_sheet/blob/main/pubspec.yaml#L8)

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[Contributor Guide]: https://github.com/woltapp/wolt_modal_sheet/blob/main/CONTRIBUTING.md

2024-02-16 08:20 UTC, ulusoyca approved these changes

2024-02-16 08:21 UTC, ulusoyca commented
@AcarFurkan Thanks for the contribution!

can you please fix the flutter analyze?

2024-02-16 08:22 UTC, ulusoyca requested changes
Can you make sure this works with the minimum supported Flutter version?

2024-02-20 09:13 UTC, AcarFurkan commented
Yes, you are right, the uri is not available in Flutter 3.7.2, so I am closing this PR.

2024-02-20 09:13 UTC, closed without merging